### ISSUE TITLE
File edit problem

### ISSUE THREAD

**Issue by stevazi** [hatoving/imscared#1]
Hi, first of all thank you for your great job, it works flawlessly! I encountered one problem only with the maze level, when the game create a file called lock.txt or lucchetto.txt and in order to go ahead you have to edit the file and write open, but I’m unable to do that , every time I edit the file and I open the game again the file is resettled to its original content, I don’t know if I do something wrong or it’s a bug… anyway again, thank you for the release and have a great day

**Comment by hatoving** [comment]
Hey there, thank you for the feedback!
The issue you have has happened to me before but only later in the game.
I'll look into it in just a sec, thanks for pointing that out!

**Comment by hatoving** [comment]
One thing: could you try deleting the file?
Thanks!

**Comment by stevazi** [comment]
I’ve tried to delete the file, I opened the game, arrived at the gate and nothing, the gate was closed and the file resetted to locked, one other thing that I’ve noted is that the html file related to this level is not being generated :) and the file is lock.txt is being created in the game asset’s root instead in the folder imscared. Thank you so much for the help!!

**Comment by hatoving** [comment]
Interesting... I'll try to fix it as soon as I can.
The way IMSCARED handles files is midly infuriating, sorry for the inconvenience 💀

**Comment by stevazi** [comment]
In the end it still an ENTITY 🤣 nice job BTW :)) have a nice day and thank you

**Comment by hatoving** [comment]
I released a new update for it. Hopefully it should fix it!
